### ISSUE TITLE
Scaffolding no longer called after composer install/update

### ISSUE THREAD

**Issue by PetersRicardo** [drupal-composer/drupal-composer-project#174] opened 2016-07-11 11:42 UTC
I'm not sure if this is intended, i couldn't find anything about it in the commit: [https://github.com/drupal-composer/drupal-project/commit/719a18806d64f2084858a2be7ebde5c049d85064]
The scaffolding calls are removed from the composer.json, and I don't see any documentation on calling `composer drupal-scaffold` to get the files needed for a `drush site-install`.
A fix is addding `"DrupalComposer\\DrupalScaffold\\Plugin::scaffold"` post-install and post-update. 

But as said I am not sure if this is intended behaviour. If it isn't I'm happy to submit the fix.

**Comment by webflo** [comment] 2016-07-11 14:29
The change is related to https://github.com/drupal-composer/drupal-project/pull/170. I think your composer is not up to date.

**Comment by fafnirical** [comment] 2016-08-02 19:39
I'm running Composer 1.2.0 (latest stable) and also running into this issue -- I have to run `composer drupal-scaffold` manually.

**Comment by Eli-TW** [comment] 2016-11-02 16:08
Same here - composer 1.2.0 and have to run composer drupal-scaffold if I have a composer.lock file checked in. 

composer-install without a lock file implements the scaffolding ok.

**Comment by jorissteyn** [comment] 2016-11-05 12:05
I can confirm the behaviour (need to manually run drupal-scaffold if composer.lock present) on composer 1.2.2 and the latest 1.3-dev (4dd2e63) snapshot.

**Comment by webflo** [comment] 2016-11-05 12:38
@jorissteyn Thats the expected behaviour, because you should commit all the scaffold files together with your lock file. You could revert 719a18806d64f2084858a2be7ebde5c049d85064 in your local installation. This would register the buildScaffold method explicitly on every install and update.

EDIT: Just look at the composer.json in the patch. The other stuff is not relevant.

**Comment by webflo** [comment] 2016-11-05 12:48
Sorry, its `@drupal-scaffold` these days.

```
diff --git a/composer.json b/composer.json
index c2f7fd5..67355d1 100644
--- a/composer.json
+++ b/composer.json
@@ -51,9 +51,11 @@
             "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
         ],
         "post-install-cmd": [
+            "@drupal-scaffold",
             "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
         ],
         "post-update-cmd": [
+            "@drupal-scaffold",
             "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
         ]
     },

```

**Comment by jorissteyn** [comment] 2016-11-05 13:30
Thanks for clearing that up. I believe it makes sense to not add the scaffolding files to git if you don't have any customizations in them, so I'll be doing that. Perhaps it's worth a mention as a FAQ in the README.

**Comment by webflo** [comment] 2016-11-05 13:36
Do you want to submit a PR?

**Comment by webflo** [comment] 2016-11-05 23:10
Thanks @jorissteyn

**Closed as completed by webflo** 2016-11-05 23:10 UTC
