### ISSUE TITLE
Composer "detaches HEAD"

### ISSUE THREAD

**Issue by albabosh** [drupal-composer/drupal-composer-project#238] opened 2017-01-29 14:46 UTC
composer create-project drupal-composer/drupal-project:7.x-dev leaves my local branch in a "detached HEAD" state (8.x remains ok, but I don't need v8).

**Comment by webflo** [comment] 2017-01-29 15:30
@albabosh Please provide some information about your dev environment (os, php version, composer version etc) Thanks!

@madalinignisca Can you help?

**Comment by albabosh** [comment] 2017-01-29 15:38
Ubuntu 14.04, PHP 5.5.9, composer 1.4-dev

**Comment by madalinignisca** [comment] 2017-01-29 17:42
```
HEAD detached at f3c2a6a
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    .travis.yml
	deleted:    LICENSE
	deleted:    README.md
	deleted:    phpunit.xml.dist

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	composer.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

This is normal when you say NO to delete .git/svn at then end of the initial setup.

At that step, it is normal to say YES to delete the .git file as you need to continue your project that will derivate from this skeleton (used to generate projects).

It's composer normal behaviour. In this situation, this is not a bug.

The changes also, come off post scripts of the skeleton that composer is supposed to run.

Please confirm and we can close the issue.

**Comment by albabosh** [comment] 2017-01-29 19:10
@madalinignisca Thanks, could you tell me the right way to correct this ?

**Comment by madalinignisca** [comment] 2017-01-30 23:05
@albabosh when you run the command to create a new project from this skeleton, at the end answer NO to the question about preserving any .git/.svn folder. That's all.

In your new folder, initialize the version control of your choice for your project as your project should not be tied to this through version control.

**Closed as completed by madalinignisca** 2017-01-30 23:05 UTC
