### ISSUE TITLE
Using Composer to Download Files

### ISSUE THREAD

**Issue by ghost** [drupal-composer/drupal-composer-project#457] opened 2019-02-10 22:59 UTC
I do not want to download Drupal in a "web" directory... I need it in my Root directory.. 
How do I download Drupal in my document root  folder?

**Comment by normanlolx** [comment] 2019-02-11 05:48
Duplicate of https://github.com/drupal-composer/drupal-project/issues/258

**Closed as completed** 2021-01-11 23:02 UTC
