### ISSUE TITLE
Ignore console/language

### ISSUE THREAD

**Issue by jcnventura** [drupal-composer/drupal-composer-project#509] opened 2019-08-24 20:06 UTC
As per https://github.com/hechoendrupal/drupal-console-core/pull/364#issuecomment-523331104, we should add console/language to the .gitignore file.

**Comment by simesy** [comment] 2020-06-24 00:50
I agree that by default it should be ignored.

**Comment by mstrelan** [comment] 2020-06-24 05:21
This is a duplicate of #508. If you have nothing custom in the `console` directory you can remove it and update drupal console to at least 1.9.3.

```
git rm -rf console
composer update drupal/console --with-dependencies
```

**Comment by normanlolx** [comment] 2021-01-11 22:24
Duplicate

**Closed as completed by normanlolx** 2021-01-11 22:24 UTC
