### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Chris-Archer-Upbeat** [drupal-composer/drupal-composer-project#459] opened 2019-02-12 19:45 UTC
Hi,

Just downloaded the latest version and run `composer install` as per the documentation, I get no errors and composer installs fine.  

However when I go to view the site I get a directly list, it looks like for some reason these files are not been installed or set up:

- web/.csslintrc
- web/.editorconfig
- web/.eslintignore
- web/.eslintrc
- web/.eslintrc.json
- web/.gitattributes
- web/.ht.router.php
- web/.htaccess
- web/autoload.php
- web/index.php
- web/robots.txt
- web/update.php
- web/web.config
- web/sites/development.services.yml
- web/sites/example.settings.local.php
- web/sites/example.sites.php
- web/sites/default/default.services.yml
- web/sites/default/default.settings.php
- web/sites/default/services.yml
- web/sites/default/settings.php

Am I missing a step, Drupal core folder is there and placeholder folders like `themes` is created.

Thanks,
Chris

**Comment by Chris-Archer-Upbeat** [comment] 2019-02-12 20:01
It seems to be related to changing `"php": ">=5.6",` to `"php": ">=7.2",`

**Comment by normanlolx** [comment] 2019-02-12 20:39
You need to provide more info to make this a reproducible problem. What OS? What Composer version? What PHP version? Did you try running `composer install` again?

**Comment by NielsSluijs** [comment] 2019-02-13 10:32
@chrisarcherhydrant Is the document root of your web server pointing to the web/ folder in your project?

**Comment by archnode** [comment] 2019-02-19 09:18
@leymannx I have the same problem on Ubuntu 18.10, PHP 7.2 and Composer 1.8.4 and also in a current alpine based docker container.

In my case it seems that drupal-scaffold fails to setup the scaffolding automatically on first install.

**Comment by zaporylie** [comment] 2019-02-20 10:34
Most likely to the composer-plugin conflict due to zaporylie/composer-drupal-optimizations dependency in drupal/core. Dependency was removed earlier today (`zaporylie/composer-drupal-optimizations:^1.1`) and your issue should be fixed @chrisarcherhydrant. Could you confirm?

**Comment by normanlolx** [comment] 2021-01-11 23:02
Closing for inactivity.

**Closed as completed by normanlolx** 2021-01-11 23:02 UTC
