### ISSUE TITLE
drush folder doesn't belong in "web" ?

### ISSUE THREAD

**Issue by yched** [drupal-composer/drupal-composer-project#20] opened 2015-05-12 21:26 UTC
... since it's not about web files ?

**Comment by webflo** [comment] 2015-05-12 21:39
Right, but i always thought needs the scope of a Drupal site. @weitzman created the PR for this feature.

@weitzman, @greg-1-anderson it there a easy solution to store the drush config outside of the webroot?

**Comment by greg-1-anderson** [comment] 2015-05-12 23:08
Really, the right solution is, as you said, to put vendor outside of the webroot.  Solve that problem, and Drush is outside of the Drupal root.

But I do agree with you.  My recommendation in my session put Drush inside the webroot as an unfortunate side-effect.  I probably should have addressed this explicitly in the session.

**Comment by yched** [comment] 2015-05-13 09:07
But vendor _is_ outside the webroot atm, right ? (the real one assembled by composer, not the one that is committed in core)

Also, just to be clear, this is only talking about the folder that holds "project-specific commandfiles, site aliases, and configuration", not the one with the drush/drush package and executables, which is already in the vendor outside the webroot :-)

**Comment by greg-1-anderson** [comment] 2015-05-13 16:29
Right.  I was thinking of a different project, for Drupal 7, that put vendor inside the docroot, and was thinking of vendor/drush/drush, not **WEBROOT**/drush, where the commandfiles go.

I opened https://github.com/drush-ops/drush/pull/1379 to consider **WEBROOT**/../drush as a default searchpath for Drush configuration and commandfiles.  If @weitzman agrees with this approach, this would allow us to put the drush folder at the project root, rather than in the web root.

**Comment by webflo** [comment] 2015-05-15 14:38
@greg-1-anderson Thanks for merging drush-ops/drush#1379 so quick. Just noticed that the `site-aliases` folder does not work either in /web/drush/sitea-aliases or /drush/site-aliases, Because [_drush_sitealias_find_alias_files](https://github.com/drush-ops/drush/blob/58320b79e0cbe2aa99e01ea2f03697bd42c44419/includes/sitealias.inc#L619) does not scan recursive.

**Comment by greg-1-anderson** [comment] 2015-05-15 15:09
Hm, maybe we should have merged that a little less quickly.  :)

Not to worry, we'll keep fixing it.  I think the best thing would be to make drush look for aliases in **CONF_DIR**/site-aliases in addition to **CONF_DIR**.

**Comment by weitzman** [comment] 2015-06-02 17:55
@greg-1-anderson - assuming you will take this on. i'm fine with whatever fix you prefer.

**Comment by webflo** [comment] 2015-07-02 18:45
@greg-1-anderson I think the issue is still open. Should i create a new issue in drush-ops/drush?

**Comment by webflo** [comment] 2015-07-02 18:46
@yched Whats your current work-a-round for this?

**Comment by rodrigoaguilera** [comment] 2015-07-02 19:16
What I do is creating aliases.drushrc.php directly in the drush folder ignoring the site-aliases folder.

**Comment by yched** [comment] 2015-07-03 13:18
> @yched Whats your current work-a-round for this?

None at the moment, I kept the current location for now :-)

**Comment by weitzman** [comment] 2015-07-06 20:35
My slight preference is to get rid of the distinct subdirs of web/drush and edit README to state that all 3 file types can be put in the drush directory. Folks who really want to segregate into subdirs can still do so. Since this is explicitly for a single project, I dont think many projects need to organize into subfolders.

**Comment by yched** [comment] 2015-07-07 12:08
@weitzman : This issue was originally about the location of the folder that contains "drush commands and config for the project" (with the idea that it doesn't belong in /web), rather than how it's internally structured - not sure if the two are related ?

On that latter aspect though, I opened #26 earlier - drush commands should IMO be split into "custom" and "contrib", just like we typically do for modules and themes (then "custom" is committed to your project repo, and "contrib" is gitignored). But that means a dedicated subfolder for commands ?

**Comment by weitzman** [comment] 2015-07-07 15:06
Oh right. Anyone can now open a PR here which moves the web/drush folder up a level.

As for the site-aliases, I'm not sure why we don't scan recursively for that. Seems like Drush should add that for consistency with the others. thoughts @greg-1-anderson?

**Comment by greg-1-anderson** [comment] 2015-07-07 17:09
I'm not sure why Drush does not search for aliases recursively; perhaps to avoid searching off in the weeds when deep hierarchies of directories exist, perhaps?

I opened https://github.com/drush-ops/drush/pull/1480 to discuss and fix.

n.b. I used 'drush/aliases' instead of 'drush/site-aliases' in that PR, which is different than the current convention in this project.  These should be made consistent before we are done here.

**Comment by greg-1-anderson** [comment] 2015-07-07 20:29
https://github.com/drush-ops/drush/pull/1480 has been merged; it now uses `drush/site-aliases` as the preferred base directory for alias files.

None of these issues really blocked what is needed here, though; site aliases search paths are not referenced in composer.json.  We just need to change `"web/drush/commands/{$name}"` to `"drush/commands/{$name}"`.  That should work fine as of https://github.com/drush-ops/drush/pull/1379.

**Comment by yched** [comment] 2015-07-13 16:46
PR opened at https://github.com/drupal-composer/drupal-project/issues/35

**Comment by webflo** [comment] 2015-10-08 08:29
Closed in favour of #35

**Closed as completed by webflo** 2015-10-08 08:29 UTC
