### ISSUE TITLE
Add a config folder and entry to default.settings.php

### ISSUE THREAD

**Issue by allgood2386** [drupal-composer/drupal-composer-project#103] opened 2016-01-26 22:01 UTC
$config_directories['git'] = '../config/';

We'd also add a config/.gitkeep file as a placeholder. This would by default set up an external directory to commit cmi to should developers be keeping that information in the repo.

**Comment by weitzman** [comment] 2016-07-08 14:36
Dupe of #86

**Closed as completed** 2016-11-05 11:20 UTC
